application:
  subdomain: ddnsgo
  background_task: true
  multi_instance: false
  routes:
    - /=http://ddnsgo.dev.beiyu.ddnsgo.lzcapp:9876/
services:
  ddnsgo:
    image: registry.lazycat.cloud/hexg/jeessy2/ddns-go:5bc8f90b73ad0415
    binds:
      - /lzcapp/var/ddns-go:/root
