package: dev.beiyu.ddnsgo
version: 6.15.0
name: DDNS-GO
description: 自动获取公网ip设置dns解析
homepage: https://github.com/jeessy2/ddns-go
author: jeessy2
locales:
  zh:
    name: DDNS-GO
    description: 简单易用的DDNS。支持阿里云、腾讯云、Dnspod、Cloudflare、Callback、华为云、百度云、Porkbun、GoDaddy、Namecheap、NameSilo等...
  en:
    name: DDNS-GO
    description: Simple and easy to use DDNS. Support Aliyun, Tencent Cloud, Dnspod, Cloudflare, Callback, Huawei Cloud, Baidu Cloud, Porkbun, GoDaddy, Namecheap, NameSilo...
permissions:
  required:
    - net.internet
