application:
  subdomain: aiclient-2-api
  background_task: true
  public_path:
    - /
  routes:
    - /=http://aiclient-2-api.cloud.lazycat.app.aiclient-2-api.lzcapp:3000/
  health_check:
    test_url: http://aiclient-2-api.cloud.lazycat.app.aiclient-2-api.lzcapp:3000/health
services:
  aiclient-2-api:
    image: registry.lazycat.cloud/hexg/justlikemaki/aiclient-2-api:c26d450a97222ba6
    binds:
      - /lzcapp/var/configs:/app/configs
    environment:
      ARGS: ""
    healthcheck:
      test:
        - CMD
        - node
        - healthcheck.js
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
