lzc-sdk-version: '0.1'
name: LobeHub
package: cloud.lazycat.app.lobehub
version: 2.0.0-next.323
description: LobeHub 是一款开源的高性能聊天机器人框架，支持多种 AI 模型
author: LobeHub
homepage: https://lobehub.com
license: MIT

# ==================== 应用入口配置 ====================
application:
  subdomain: lobehub
  # OIDC 回调路径，启用后系统会自动注入 OIDC 相关环境变量
  oidc_redirect_path: /api/auth/callback/oidc
  # HTTP 路由规则
  routes:
    - /=http://lobe.cloud.lazycat.app.lobehub.lzcapp:3210
    # MinIO S3 代理路由（用于文件上传/下载）
    - /s3/=http://minio.cloud.lazycat.app.lobehub.lzcapp:9000/

# ==================== 服务配置 ====================
services:
  # -------------------- PostgreSQL 数据库 --------------------
  postgresql:
    image: registry.lazycat.cloud/hexg/pgvector/pgvector:22d3d958eb148973
    binds:
      - /lzcapp/var/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=lobechat
      - POSTGRES_PASSWORD={{ stable_secret "pg_password" }}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      start_period: 30s

  # -------------------- Redis 缓存 --------------------
  redis:
    image: registry.lazycat.cloud/hexg/library/redis:f58bf348bfac3995
    command: redis-server --save 60 1000 --appendonly yes
    binds:
      - /lzcapp/var/redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      start_period: 10s

  # -------------------- MinIO 对象存储 --------------------
  minio:
    # minio/minio:RELEASE.2025-04-22T22-12-26Z
    image: registry.lazycat.cloud/hexg/minio/minio:42864c379f3e3b17
    binds:
      - /lzcapp/var/minio:/data
    environment:
      - MINIO_API_CORS_ALLOW_ORIGIN=*
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD={{ stable_secret "minio_password" }}
    entrypoint: >
      /bin/sh -c "
        minio server /data --address ':9000' --console-address ':9001' &
        MINIO_PID=$$!
        while ! curl -s http://localhost:9000/minio/health/live; do
          echo 'Waiting for MinIO to start...'
          sleep 1
        done
        sleep 3
        mc alias set myminio http://localhost:9000 admin {{ stable_secret "minio_password" }}
        mc mb --ignore-existing myminio/lobe
        wait $$MINIO_PID
      "
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      start_period: 30s

  # -------------------- SearXNG 搜索引擎 --------------------
  searxng:
    #image: searxng/searxng
    image: registry.lazycat.cloud/hexg/searxng/searxng:8488f3c4169da12d
    environment:
      - SEARXNG_BASE_URL=https://${LAZYCAT_APP_DOMAIN}/searxng

  # -------------------- LobeHub 主服务 --------------------
  lobe:
  #image: lobehub/lobehub
    image: registry.lazycat.cloud/hexg/lobehub/lobehub:201e1d8986791fe9
    depends_on:
      - postgresql
      - redis
      - minio
    environment:
      # ========== LobeHub 基础配置 ==========
      - APP_URL=https://${LAZYCAT_APP_DOMAIN}
      - AUTH_URL=https://${LAZYCAT_APP_DOMAIN}/api/auth

      # ========== 数据库配置 ==========
      - DATABASE_URL=postgresql://postgres:{{ stable_secret "pg_password" }}@postgresql.cloud.lazycat.app.lobehub.lzcapp:5432/lobechat

      # ========== Redis 配置 ==========
      - REDIS_URL=redis://redis.cloud.lazycat.app.lobehub.lzcapp:6379
      - REDIS_PREFIX=lobechat
      - REDIS_TLS=0

      # ========== 安全密钥配置 ==========
      - NEXT_AUTH_SECRET={{ stable_secret "nextauth_secret" }}
      - KEY_VAULTS_SECRET={{ stable_secret "vaults_secret" }}

      # ========== SSO OIDC 配置（使用懒猫微服统一认证）==========
      - NEXT_AUTH_SSO_PROVIDERS=oidc
      - AUTH_OIDC_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
      - AUTH_OIDC_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
      - AUTH_OIDC_ISSUER=${LAZYCAT_AUTH_OIDC_ISSUER_URI}

      # ========== S3 对象存储配置（MinIO）==========
      - S3_ENDPOINT=http://minio.cloud.lazycat.app.lobehub.lzcapp:9000
      - S3_PUBLIC_DOMAIN=https://${LAZYCAT_APP_DOMAIN}/s3
      - S3_BUCKET=lobe
      - S3_ACCESS_KEY_ID=admin
      - S3_SECRET_ACCESS_KEY={{ stable_secret "minio_password" }}
      - S3_ENABLE_PATH_STYLE=1
      - S3_SET_ACL=0
      - LLM_VISION_IMAGE_USE_BASE64=1

      # ========== 搜索引擎配置 ==========
      - SEARXNG_URL=http://searxng.cloud.lazycat.app.lobehub.lzcapp:8080