package: cloud.lazycat.app.lobehub
version: 2.1.48
name: LobeHub
homepage: https://github.com/lobehub/lobe-chat
author: LobeHub
license: LobeHub Community License
min_os_version: 1.5.0
locales:
  zh:
    name: LobeHub
    description: LobeHub 是一个工作与生活空间，用于发现、构建并与会随着您一起成长的 Agent 队友协作。在 LobeHub 中，我们将 Agent 视为工作单元，提供一个让人类与 Agent 共同进化的基础设施。
  en:
    name: LobeHub
    description: LobeHub is the ultimate space for work and life:to find, build, and collaborate with agent teammates that grow with you.We’re building the world’s largest human–agent co-evolving network.
permissions:
  optional:
    - net.internet
