lzc-sdk-version: '0.1'
name: MoviePilot
package: cloud.lazycat.app.movie-pilot
version: 0.9.1+2.8.1-1
description: 媒体库自动化管理
homepage: https://github.com/hexgu/LazyCat-Packages
author: Hexg
application:
  subdomain: movie-pilot
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://movie-pilot:3000/
services:
  movie-pilot:
    image: ghcr.nju.edu.cn/jxxghp/moviepilot:2.8.1-1
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - SUPERUSER=admin
      - MOVIEPILOT_AUTO_UPDATE=false
      - GITHUB_PROXY=https://ghfast.top/
      - PIP_PROXY=https://mirrors.cernet.edu.cn/pypi/simple/
      - CACHE_BACKEND_TYPE=redis
      - CACHE_BACKEND_URL=redis://:redis_password@redis:6379
    binds:
      - /lzcapp/var/config:/config
      - /lzcapp/pkg/content:/moviepilot/.cache/ms-playwright
      - /lzcapp/run/mnt/home:/home
  redis:
    volumes:
        - /lzcapp/var/redis:/data
    image: registry.lazycat.cloud/hexg/library/redis:d32c277b2bdcbb23
    command: redis-server --save 600 1 --requirepass redis_password