package: cloud.lazycat.app.altus
version: 5.7.2+1.0.4

author: Hexg
homepage: https://github.com/hexgu/LazyCat-Packages

# 核心容器配置
application:
  subdomain: altus
  # 自动启动且不休眠
  background_task: true
  # 支持多实例部署
  multi_instance: false
  # health_check:
  #   test_url: http://altus:3000/
  routes:
    - /=http://altus:7396/
locales:
  zh:
    name: PCSX2
    description: PCSX2 是一个开源的 PS2 模拟器。
  en:
    name: PCSX2
    description: PCSX2 is an open source PS2 Emulator.

services:
  pcsx2:
    #image: ghcr.nju.edu.cn/linuxserver/pcsx2:latest
    image: ghcr.nju.edu.cn/linuxserver/foldingathome:latest
    environment:
      TZ: "Asia/Shanghai"
    binds:
      - /lzcapp/var/config:/config
    shm_size: "1gb"