application:
  subdomain: portainer
  oidc_redirect_path: /auth/oidc.callback
  background_task: false
  multi_instance: false
  public_path:
    - /
  routes:
    - /=http://portainer.cloud.lazycat.app.portainer.lzcapp:9000/
services:
  portainer:
    image: dockerproxy.net/6053537/portainer-ce:latest
    binds:
      - /lzcapp/var/data:/data
