name: wakapi
package: cloud.lazycat.app.wakapi
version: 2.17.1
homepage: https://github.com/hexgu/LazyCat-Packages
author: Hexg
locales:
  zh:
    name: wakapi
    description: 📊 一款极简、自托管且兼容 WakaTime 的代码统计后端
  en:
    name: wakapi
    description: 📊 A minimalist, self-hosted WakaTime-compatible backend for coding statistics
application:
  oidc_redirect_path: /oidc/lazycat/callback
  background_task: true
  subdomain: wakapi
  routes:
    - /=http://wakapi:3000/
  health_check:
    test_url: http://wakapi:3000/api/health
  public_path:
    - /
services:
  wakapi:
    environment:
        - WAKAPI_PASSWORD_SALT={{ stable_secret "WAKAPI_PASSWORD_SALT"}}
        - WAKAPI_EXPOSE_METRICS=true
        - WAKAPI_DISABLE_LOCAL_AUTH=true
        - WAKAPI_OIDC_ALLOW_SIGNUP=true
        - WAKAPI_OIDC_PROVIDERS_0_NAME=lazycat
        - WAKAPI_OIDC_PROVIDERS_0_DISPLAY_NAME=LazyCat
        - WAKAPI_OIDC_PROVIDERS_0_CLIENT_ID=${LAZYCAT_AUTH_OIDC_CLIENT_ID}
        - WAKAPI_OIDC_PROVIDERS_0_CLIENT_SECRET=${LAZYCAT_AUTH_OIDC_CLIENT_SECRET}
        
        # 1. 尝试不使用自动探测，直接指定 Issuer
        - WAKAPI_OIDC_PROVIDERS_0_ENDPOINT=${LAZYCAT_AUTH_OIDC_ISSUER_URI}
        
        # 2. 增加这个关键配置：指定额外的 Scopes。
        # 有些系统必须看到 groups 才会返回详细 userinfo
        - WAKAPI_OIDC_PROVIDERS_0_SCOPES=openid,profile,email,groups
        
        # 3. 切换 Claim 目标
        # 既然 sub/preferred_username 不行，尝试 email
        # 如果 email 也不行，说明懒猫必须通过 UserInfo 接口读取，而 Wakapi 可能在 ID Token 解析阶段就退出了
        # - WAKAPI_OIDC_PROVIDERS_0_USERNAME_CLAIM=email
        
        - WAKAPI_PUBLIC_URL=https://${LAZYCAT_APP_DOMAIN}
        - WAKAPI_INSECURE_COOKIES=true
    volumes:
        - /lzcapp/var/data:/data
    image: registry.lazycat.cloud/hexg/muety/wakapi:a7b33301db87b740