package: cloud.lazycat.app.new-api
version: 0.10.8+1.2.2
name: New API
description: AI模型聚合管理中转分发系统，一个应用管理您的所有AI模型，支持将多种大模型转为统一格式调用，支持OpenAI、Claude、Gemini等格式，可供个人或者企业内部管理与分发渠道使用。
author: Calcium-Ion
homepage: https://github.com/QuantumNous/new-api
license: New-API-License
locales:
  zh:
    name: New API
    description: 🍥 下一代LLM网关和AI资产管理系统
  en:
    name: New API
    description: 🍥 Next-Generation LLM Gateway and AI Asset Management System
permissions:
  optional:
    - net.internet
