package: cloud.lazycat.app.peerbanhelper
version: 9.3.10
name: PeerBanHelper
homepage: https://github.com/hexgu/LazyCat-Packages
author: Hexg
locales:
  zh:
    name: PeerBanHelper
    description: BT 反吸血工具 - 自动封禁不受欢迎、吸血和异常的 BT 客户端，并支持自定义规则。支持 qB/qBEE/Deluge/BiglyBT/BitComet
  en:
    name: PeerBanHelper
    description: BT Anti-Leech Tool - Automatically ban unpopular, leeching, and abnormal BT clients, and supports custom rules. Supports qB/qBEE/Deluge/BiglyBT/BitComet
permissions:
  required:
    - net.lan
  optional:
    - net.internet
